### ISSUE TITLE
能否增加一些控制台打印信息

### ISSUE THREAD

**Issue by eros1018** [cssxsh/mirai-new-bing#8]
初次使用比较难判断是config文件配置异常，还是权限未配置
另外bing的响应时间比较长，有时候不知道是插件没配好还是在等待bing返回
能否增加一些打印信息，启动时自检代理链接异常、权限是否配置等，以及触发调用时打印输入及响应情况

**Comment by cssxsh** [comment]
> 自检代理链接异常

不可能做到的
