### ISSUE TITLE
纯新手，想问下如何看权限ID，日志是啥……

### ISSUE THREAD

**Issue by himetuki** [cssxsh/mirai-new-bing#9]
日志是运行cmd时候上面自动加载的那些吗？倒是找到两个
xyz.cssxsh.mirai.bing.MiraiNewBingListener
和
xyz.cssxsh.mirai:mirai-new-bing

**Comment by cssxsh** [comment]
如果日志刷太快看不过来就看 `logs` 下面的日志文件
